### ISSUE TITLE
Move devbot to be running on the dev rancher environment

### ISSUE THREAD

**Issue by Hodgy** [UniversityOfNottingham/devbot#12]
A few planned features will require devbot to be able to access internal only services so will need to be moved to sit within the internal network

**Comment by beforan** [comment]
we'll need `docker-compose.yml` and `rancher-compose.yml` and we'll need to have them get environment variables from the machine that runs `rancher-compose up` (i.e. not have those variables in source control).

All pretty straightfoward though.

**Comment by Hodgy** [comment]
Putting it on the dev instance may not work. I believe external things will be able to communicate with the bot
